apiVersion: v2
name: mobile-api
description: Helm chart for mobile-api app
type: application
version: 0.0.7
appVersion: "0.0.31"
keywords:
- mobile-api
maintainers:
- name: Ioan Damian
  email: ioan@tranzy.ai
